bsoc-bitbyte/GetIt

- pages/index.vue
Added the index.vue file inside the pages folder as required.
@Priyansh61 @prernadabi23
> added index.vue inside the pages folder

- pages/Signin.vue
- pages/Signup.vue
1. This PR fixes or fixes part of #7 
2. This PR is a continuation of the PR #17 
3. 
Desktop view of the pages:
Mobile View:
PTAL @thejaysharma @Priyansh61 @prernadabi23
> Continuation to pr-17

- backend/auth/urls.py
- backend/core/settings.py
- backend/core/urls.py
- backend/requirements.txt
1. This PR fixes #39 
2. This PR does the following:
- add an endpoint to get `access` and `refresh` tokens from username and password
- another endpoint to get `access` token from `refresh`
> feat(backend): setup authentication

- pages/Signin.vue
- pages/Signup.vue
1. This PR fixes or fixes part of #56 
2. This PR does the following: Fixed the responsiveness issue of both the pages.
3. Made them responsive for all devices including mobile/laptop/tablets.
4. Incorporated form in both pages compared to the hard coded sub-parts before
Mobile Views:
Tablet Views:
Desktop/Laptop Views:
PTAL @Priyansh61 @prernadabi23 @tushitshukla03 @prernadabi23
> Fixed signup and signin pages

- pages/products/_id.vue
> Revert "fix: Made the color palette go below the product image"

- pages/Signin.vue
1) This PR fixes the issue or part of issue #81 
2) Fixed the image dimensions in Signin page to make it similar to SIgnup and minimise transition
[GetIt.webm](https://github.com/bsoc-bitbyte/GetIt/assets/123197237/e593cfb7-10fa-4f63-8cde-790ce605e574)
PTAL @prernadabi23 @Priyansh61 @tushitshukla03 @thejaysharma
> Fixed the image dimensions

- components/Nav.vue
- layouts/default.vue
- pages/Signup.vue
- pages/cart.vue
- pages/checkOut.vue
- pages/index.vue
1. This PR fixes or fixes part of #23.
2. This PR does the following: adds navbar to all the routes
> Adds Navbar to all the Routes

- backend/accounts/admin.py
- backend/accounts/models.py
- backend/accounts/tests.py
- backend/accounts/views.py
- backend/build.py
- backend/core/settings.py
- backend/requirements.txt
> fix(backend): fix account and build file

- backend/core/settings.py
- backend/core/urls.py
- backend/products/admin.py
- backend/products/apps.py
- backend/products/models.py
- backend/products/tests.py
- backend/products/views.py
- backend/requirements.txt
1. This PR fixes or fixes part of None
2. This PR does the following: Adds Product, Prdduct Variation, Size and Colour Model
> feat (backend) : Added Product Models

- pages/Signin.vue
- pages/Signup.vue
1. This PR fixes or fixes part of #95 .
2. This PR does the following: [This pr makes the remember me checkbox allign]
> Made the remember me checkbox alligned

- components/Nav.vue
- pages/products/_id.vue
1. This PR fixes or fixes part of #99 .
2. This PR does the following: Removed dark mode from codebase.
> Removed Dark mode

- nuxt.config.js
- package-lock.json
- package.json
- pages/cart.vue
- pages/products/_id.vue
- plugins/vuex-persist.js
- store/index.js
1. This PR fixes or fixes part of #90 .
2. This PR does the following: makes the 'Add to Cart' and 'Remove from cart(Cross X)',increment (+) and decrement(-) buttons functional. The Cart page now displays the items added to the cart by the user by retrieving data from Vuex store. The Vuex store is persisted across browser refreshes/sessions as it is saved in the local storage of the browser. The User is notified about adding/removing/increments/decrements of products through informative toast notifications.
https://github.com/bsoc-bitbyte/GetIt/assets/119884665/9c93d256-3d4d-41b7-b822-180a6f707d94
this below preview is for "storing on local storage"
https://github.com/bsoc-bitbyte/GetIt/assets/119884665/ea9cf6f6-365f-4816-bb0b-22df73d32260
@tushitshukla03 PTAL
> feat: add to cart btn functionality

- backend/accounts/serializers.py
- backend/core/settings.py
- backend/core/urls.py
- backend/events/admin.py
- backend/events/apps.py
- backend/events/models.py
- backend/events/serializers.py
- backend/events/tests.py
- backend/events/urls.py
- backend/events/views.py
1. This PR adds events model with serializer and everything
> feat : Added Events Model

- backend/core/settings.py
1. This PR fixes or fixes part of #111 .
> Fix: Added Frontend Origin in CORS whitelist

- backend/events/permissions.py
- backend/events/tests.py
- backend/events/views.py
> add tests and permissions for event app

- backend/events/permissions.py
- backend/events/tests.py
- backend/tickets/models.py
- backend/tickets/permissions.py
- backend/tickets/serializers.py
- backend/tickets/test_tickets_crud.py
- backend/tickets/tests.py
- backend/tickets/urls.py
- backend/tickets/views.py
1. This PR fixes #118 .
2. This PR does the following: 
1. Add tests for the allowed CRUD operations.
2. Add default for status in ticket model
3. Allow only read-only operations on status for now
4. Allow only Create, List and Retrieve actions on `Ticket`.
5. Restrict permissions for the endpoint
> add tests for tickets app and other changes

- backend/core/settings/base.py
- backend/core/urls.py
- backend/requirements.txt
1. This PR fixes #107 
2. This PR does the following: Adds the swagger documentation
> feat: added swagger api docs

- backend/core/settings/base.py
- backend/core/urls.py
- backend/orders/admin.py
- backend/orders/models.py
- backend/orders/permissions.py
- backend/orders/serializers.py
- backend/orders/urls.py
- backend/orders/views.py
- backend/products/admin.py
- backend/products/models.py
- backend/products/serializers.py
- backend/products/urls.py
- backend/products/views.py
> simplify products and add orders model

- backend/accounts/views.py
- backend/core/urls.py
- backend/core/views.py
- backend/tickets/urls.py
- backend/tickets/views.py
- frontend/pages/checkOut.vue
- frontend/store/auth.js
> Added UPI integration with the App and setup the webhook

- backend/products/models.py
- frontend/components/Nav.vue
- frontend/components/NavNew.vue
- frontend/pages/Signin.vue
- frontend/pages/Signup.vue
- frontend/store/auth.js
> Feat : Added minor changes to make UX better

- frontend/pages/cart.vue
> Replace Rs with ₹

- frontend/components/NavNew.vue
- frontend/package-lock.json
- frontend/pages/cart.vue
- frontend/pages/events/[id].vue
> improved cart total

- backend/orders/serializers.py
- frontend/pages/checkOut.vue
- frontend/pages/payment/[id].vue
- frontend/store/auth.js
> Minor Fixes 

- frontend/components/NavNew.vue
- frontend/pages/Signin.vue
- frontend/pages/checkOut.vue
- frontend/pages/order.vue
> minor ux improvements

- frontend/pages/events/[id].vue
> render html in description

- frontend/components/NavNew.vue
- frontend/pages/events/[id].vue
> route to 404 in case of event not found , fixes issue #159

- backend/accounts/models.py
- backend/orders/admin.py
> Updated admin panel for better understanding of orders

- .github/workflows/gpt-review.yml
> add gpt pr reviewer

- backend/tickets/views.py
> fix: add branch to form data

- frontend/store/auth.js
Removed a line used for Debugging purpose which was actually showing email and password in console after sign in.
> Removed a line of code used for Debugging purpose

- frontend/components/eventList.vue
1. This PR fixes or fixes part of #189 .
2. This PR does the following: Redesigned the event card component designed according to the figma file.
https://github.com/bsoc-bitbyte/GetIt/assets/156583847/63d6c7da-9d0a-4585-b0b3-2f079b9d47ac
> Fix#189: Redesigned the event card

- frontend/pages/index.vue
- package-lock.json
1. This PR fixes or fixes part of #198   .
2. This PR does the following: create a event and merch card
https://github.com/bsoc-bitbyte/GetIt/assets/149250431/a8fe1a74-a371-4099-b516-d05263fa2abf
https://github.com/bsoc-bitbyte/GetIt/assets/149250431/93a58d58-ff25-49aa-b702-c9d0ebc29fa7
> #202 :feat(index_page): create components for events and merchandise cards

- backend/core/settings/base.py
- backend/products/views.py
1. This PR fixes or fixes part of #223 
2. This PR does the following:
Modifies the products fetching logic to include sorting and filtering of products
> feat : adds sorting and filtering features to the products fetching API

- backend/core/settings/base.py
- backend/products/views.py
1. This PR fixes or fixes part of #224 
2. This PR does the following: adds pagination to the products api endpoint
> feat : Adds pagination to the products api endpoint

- frontend/components/SizeSelector.vue
1. This PR fixes or fixes part of #214 .
2. This PR does the following: Made a SizeSelector Component according to the style given in figma file and added availableSizes and selectedSizes props and Implemented update:selectedSizes emit for parent communication
https://github.com/user-attachments/assets/8e46e6e9-f708-48ca-b532-e423afc64261
Closes #214 
Please review @Vaibhavsahu2810
> Fix #214: feat: Made a size selection component with parent child communication with props
